// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_qiMNwYNU7t0FnegdvdwQ7IRiG6pdQnQ',
    appId: '1:1003955092966:web:c0299e2136e6c6595d2a27',
    messagingSenderId: '1003955092966',
    projectId: 'cinemabookingapp-e1573',
    authDomain: 'cinemabookingapp-e1573.firebaseapp.com',
    storageBucket: 'cinemabookingapp-e1573.firebasestorage.app',
    measurementId: 'G-N3KFJEVPB6',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbMew0m533KbHpgZYeeiBp70vZqRsw_EM',
    appId: '1:1003955092966:ios:f13298580e5f35bb5d2a27',
    messagingSenderId: '1003955092966',
    projectId: 'cinemabookingapp-e1573',
    storageBucket: 'cinemabookingapp-e1573.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbMew0m533KbHpgZYeeiBp70vZqRsw_EM',
    appId: '1:1003955092966:ios:f13298580e5f35bb5d2a27',
    messagingSenderId: '1003955092966',
    projectId: 'cinemabookingapp-e1573',
    storageBucket: 'cinemabookingapp-e1573.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_qiMNwYNU7t0FnegdvdwQ7IRiG6pdQnQ',
    appId: '1:1003955092966:web:7ac9763a35b8160a5d2a27',
    messagingSenderId: '1003955092966',
    projectId: 'cinemabookingapp-e1573',
    authDomain: 'cinemabookingapp-e1573.firebaseapp.com',
    storageBucket: 'cinemabookingapp-e1573.firebasestorage.app',
    measurementId: 'G-RK5HMCSPJX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIgeMBoji_90-HOYQi68KSf9Qjb4AY9VE',
    appId: '1:1003955092966:android:cb2e68fc40601ba45d2a27',
    messagingSenderId: '1003955092966',
    projectId: 'cinemabookingapp-e1573',
    storageBucket: 'cinemabookingapp-e1573.firebasestorage.app',
  );
}
